- hosts: my_existing_vms_polyakov
  become: yes
  tasks:
    - name: Update apt cache and install required packages if not installed
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - cmatrix
          - cowsay
          - sl
